Fix better accurateblockplacement
senseiwells/EssentialClient pull request #60
Opened 2022-07-26 12:35 UTC by aria1th

Fixes ghost block issues with pistons
Fixes FakeDirection not being nullified

2022-07-28 20:01 UTC, senseiwells requested changes

2022-07-28 20:01 UTC, senseiwells commented on src/main/java/me/senseiwells/essentialclient/feature/BetterAccurateBlockPlacement.java
> +		}
This is super messy and hard to read. Have a look at: https://github.com/senseiwells/ArucasLibraries/blob/master/libs/minecraft/PosUtils.arucas#L78-L116. (In arucas but that doesn't really matter.

2022-07-28 20:51 UTC, senseiwells approved these changes

2022-08-06 17:44 UTC, aria1th commented
merged to #67

2022-08-06 17:44 UTC, closed without merging